### ISSUE TITLE
Add isString assertion

### ISSUE THREAD

**Issue by aspyatkin** [guillaumepotier/validator.js#32]
Hey, I am implementing form validation for Express.js application with your library. I have ran into a small problem.
I have one string field with only length limit. So I wrote the following constraint for that field:
``` javascript
new Assert().Length(min: 0, max: 150)  // it's up to user whether to fill the field or not
```
The data comes from urlencoded POST request, and is parsed by `express-bodyparser` library. Imagine the field is called `locality`, and the submitted form data is `locality=one&locality=two&locality=three`. When `express-bodyparser` parses this, I get an object `{locality: ['one', 'two', 'three']}`. So, with the aforementioned constraint validation will pass. I want validation to fail when the submitted data is not a string to avoid such situation. There is `InstanceOf` assertion in the library, but
``` javascript
('test' instanceof String) === false
```
so I can't use that. Now I'm using a callback assertion:
``` javascript
toString.call(value) === '[Object String]'
```
taken from is.js library.
Finally, I would like to propose to add `IsString` assertion to your library. I think it might be useful.

**Comment by guillaumepotier** [comment]
Hi there,

Thanks for using Validator.js. I do not see any problem adding a `isString` validator no :)

Feel free to do so, add some tests and documentation, than submit a PR.

Best
