### ISSUE TITLE
Incompatibility with `Extend` and `Pretty Constructors`

### ISSUE THREAD

**Issue by franciscocardoso** [guillaumepotier/validator.js#57]
## Entend

The Assert class can be extended by using  the`Extend` feature. Besides adding custom asserts this allows us to override any of the asserts available in the module. Let's say that someone needs to tweak the behaviour of an existing Assert, [Required](https://github.com/guillaumepotier/validator.js/issues/29) per instance.

You can achieve this by doing something like this:

``` js
const BaseAssert = require('validator.js').Assert;

// Load your customer asserts, including your tweaked Required.
const customAsserts = require('path-to-custom-asserts');

module.exports = {
  Assert: BaseAssert.extend(customerAsserts)
};

```

And you are done. At this point you can use your own `Required` assert.

``` js
new Assert().Required();
```
## Pretty constructors

With the introduction of this feature we can write this with less code, which is awesome. You can simply write:

``` js
is.required();
```
## Problem

The behaviour will be different for each of the calls.

``` js
new Assert().Required(); // This will result in using the overridden assert.
```

``` js
is.required(); // This will result in using the original assert.
```

This is due to the cache mechanism added to the [_prettify](https://github.com/guillaumepotier/validator.js/blob/master/src/validator.js#L1086) method which prevents any existing Assert from being overridden.
## Solutions

I believe that the solution will depend on the desired behaviour. 
- Should we "fix" the caching mechanism to allow any original assert to be overridden?
- Should we prevent _.extend()_ from overriding original asserts?

How should we approach this issue?

**Comment by franciscocardoso** [comment]
WTYD @guillaumepotier ?

**Comment by guillaumepotier** [comment]
Hi, thanks for this quite long and explaining issue.

I think this is related somehow with #29 as the original `Required` were kinda bloated no? I mean, user should not have a need to override an existing `Assert` as they should be atomic (not the case for `Require`) and "built-in" right?

We should allow user to define its own Assert, and that should be done in the pretty way too like the others built-in, but not being able to override them does not seem a serious matter to me.

**Comment by franciscocardoso** [comment]
Hi, 

Indeed, one thing leads to another.
I'll create a PR disallowing override asserts when extending.

Thanks!
