### ISSUE TITLE
Collaboration request

### ISSUE THREAD

**Issue by franciscocardoso** [guillaumepotier/validator.js#66]
Hi @guillaumepotier,

As previously discussed, can you please add [Francisco Cardoso](https://github.com/franciscocardoso), [Nuno Sousa](https://github.com/nunofgs), [Ricardo Lopes](https://github.com/rplopes), [Rui Marinho](https://github.com/ruimarinho) and [Tiago Ribeiro](https://github.com/fixe) as collaborators in the project?

Looking forward to it!

🍻

**Comment by guillaumepotier** [comment]
Hi there,

This is done, everyone is collaborator now 🎉 

I added a small constraint rule on master branch : everyone must submit a PR to update it, with at least one review, up to date and tests passing :)

Feel free to comment, or close this issue if everything is ok with you like that.

Happy contributing!

Best

**Comment by franciscocardoso** [comment]
> I added a small constraint rule on master branch : everyone must submit a PR to update it, with at least one review, up to date and tests passing :)

Awesome!!

Thank you very much. Let the games begin. 😄
